services:
  # Backend API
  - type: web
    name: pass-backend-api
    runtime: docker
    dockerContext: .
    dockerfilePath: pass_backend/Dockerfile
    envVars:
      - key: PORT
        value: 3333
      - key: DATABASE_HOST
        fromDatabase:
          name: pass-postgres-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: pass-postgres-db
          property: port
      - key: DATABASE_USER
        fromDatabase:
          name: pass-postgres-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: pass-postgres-db
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: pass-postgres-db
          property: database
      # Using the external MinIO user provided
      - key: MINIO_ENDPOINT
        value: minio-latest-q46m.onrender.com
      - key: MINIO_PORT
        value: 443 # HTTPS standard port
      - key: MINIO_USE_SSL
        value: true
      - key: MINIO_ACCESS_KEY
        sync: false
      - key: MINIO_SECRET_KEY
        sync: false

databases:
  - name: pass-postgres-db
    databaseName: pass_db
    user: pass_user
    plan: free # Managed PostgreSQL Free Tier
